language: python
python:
	- "3.5"
	- "3.6"
	- "3.7"
	- "3.8"
	- "3.9"
	
services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="api.settings"
    - PYTHONPATH="/home/travis/build/Dillonsd/CollectiblesDB"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=3.1.3 DB=mysql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test
