language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
services: mysql

env:
  - DJANGO=3.1.3 DB=mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;'

script:
  - python manage.py test
